"""generate_report.py — 从 run_fund.py 的 JSON 结果生成 PDF 报告

用法:
    python generate_report.py --input results/run_xxx.json --output results/report.pdf

依赖（自动检测）:
    fpdf2 (pip install fpdf2) — 首选
    如不可用，生成 HTML 替代
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False


def _safe_str(val, max_len=60):
    s = str(val) if val is not None else "-"
    return s[:max_len]


def generate_html_report(data: dict, output_path: str) -> str:
    """生成 HTML 报告（fallback 模式或直接使用）。"""
    tickers = data.get("tickers", [])
    run_time = data.get("run_time", datetime.now().isoformat())
    signals = data.get("analyst_signals", {})
    risk = data.get("risk_data", {})
    decisions = data.get("decisions", {})

    # 摘要行
    summary_rows = ""
    for t in tickers:
        d = decisions.get(t, {})
        summary_rows += f"""
        <tr>
            <td>{t}</td>
            <td><strong>{d.get('action', '-').upper()}</strong></td>
            <td>{d.get('quantity', 0)}</td>
            <td>{d.get('confidence', 0)}%</td>
            <td>{d.get('reasoning', '-')[:80]}</td>
        </tr>"""

    # 信号矩阵
    signal_rows = ""
    agent_keys = [k for k in signals.keys() if k != "risk_management_agent"]
    for t in tickers:
        for ak in agent_keys:
            s = signals.get(ak, {}).get(t, {})
            sig = s.get("signal", "-")
            conf = s.get("confidence", 0)
            reason = s.get("reasoning", "-")[:60]
            color = {"bullish": "#22c55e", "bearish": "#ef4444", "neutral": "#94a3b8"}.get(sig, "#000")
            signal_rows += f"""
            <tr>
                <td>{t}</td>
                <td>{ak}</td>
                <td style="color:{color};font-weight:bold">{sig.upper()}</td>
                <td>{conf}%</td>
                <td style="font-size:12px">{reason}</td>
            </tr>"""

    # 风险行
    risk_rows = ""
    for t in tickers:
        r = risk.get(t, {})
        vol = r.get("volatility_metrics", {})
        risk_rows += f"""
        <tr>
            <td>{t}</td>
            <td>{r.get('current_price', '-')}</td>
            <td>{r.get('remaining_position_limit', 0):,.0f}</td>
            <td>{vol.get('annualized_volatility', 0):.1%}</td>
            <td>{vol.get('data_points', 0)}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<title>AI Hedge Fund 分析报告</title>
<style>
    body {{ font-family: 'Segoe UI', 'Microsoft YaHei', sans-serif; max-width: 900px; margin: auto; padding: 20px; color: #1e293b; }}
    h1 {{ text-align: center; font-size: 28px; margin-bottom: 5px; }}
    .subtitle {{ text-align: center; color: #64748b; margin-bottom: 30px; }}
    h2 {{ border-bottom: 2px solid #e2e8f0; padding-bottom: 5px; margin-top: 30px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 10px 0 20px; }}
    th, td {{ border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }}
    th {{ background: #f1f5f9; font-weight: 600; }}
    .disclaimer {{ background: #fef3c7; border: 1px solid #f59e0b; padding: 15px; margin-top: 30px; border-radius: 6px; font-size: 13px; color: #92400e; }}
    .footer {{ text-align: center; color: #94a3b8; font-size: 12px; margin-top: 30px; }}
</style>
</head>
<body>

<h1>AI Hedge Fund 分析报告</h1>
<p class="subtitle">生成时间: {run_time} | 股票: {', '.join(tickers)}</p>

<h2>一、最终决策摘要</h2>
<table>
    <tr><th>股票</th><th>操作</th><th>数量</th><th>置信度</th><th>理由</th></tr>
    {summary_rows}
</table>

<h2>二、分析师信号矩阵</h2>
<table>
    <tr><th>股票</th><th>分析师</th><th>信号</th><th>置信度</th><th>推理</th></tr>
    {signal_rows}
</table>

<h2>三、风险与仓位数据</h2>
<table>
    <tr><th>股票</th><th>当前价格</th><th>仓位上限</th><th>年化波动率</th><th>数据天数</th></tr>
    {risk_rows}
</table>

<div class="disclaimer">
    <strong>免责声明</strong><br>
    本报告由 AI Hedge Fund Skill 自动生成，所有交易建议<b>仅用于研究和教育目的</b>，不构成投资建议。
    过去表现不代表未来结果。真实交易前请咨询持牌投资顾问。使用者自负盈亏。
</div>

<p class="footer">Generated by AI Hedge Fund Skill (WorkBuddy Edition) — github.com/Abyss-Seeker/ai-hedge-fund-skill</p>

</body>
</html>"""

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    return output_path


def generate_pdf_report(data: dict, output_path: str) -> str:
    """生成 PDF 报告（首选 fpdf2，fallback 到 HTML）。"""
    if not HAS_FPDF:
        html_path = output_path.replace(".pdf", ".html")
        generate_html_report(data, html_path)
        print(f"[report] fpdf2 未安装，已生成 HTML 替代: {html_path}")
        print("[report] 安装 fpdf2 以直接生成 PDF: pip install fpdf2")
        return html_path

    pdf = FPDF()
    pdf.add_page()

    # 中文字体（尝试常见路径）
    font_paths = [
        "C:/Windows/Fonts/msyh.ttc",
        "C:/Windows/Fonts/simsun.ttc",
        "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
        "/System/Library/Fonts/PingFang.ttc",
    ]
    font_loaded = False
    for fp in font_paths:
        if Path(fp).exists():
            try:
                pdf.add_font("zh", "", fp, uni=True)
                pdf.add_font("zh", "B", fp, uni=True)
                font_loaded = True
                break
            except Exception:
                continue

    if not font_loaded:
        # fallback 到 HTML
        html_path = output_path.replace(".pdf", ".html")
        print("[report] 未找到中文字体，已生成 HTML 替代")
        return generate_html_report(data, html_path)

    tickers = data.get("tickers", [])
    run_time = data.get("run_time", "")
    signals = data.get("analyst_signals", {})
    risk = data.get("risk_data", {})
    decisions = data.get("decisions", {})

    def write_title(text, size=18):
        pdf.set_font("zh", "B", size)
        pdf.cell(0, 12, text, ln=True)
        pdf.ln(4)

    def write_normal(text, size=10):
        pdf.set_font("zh", "", size)
        pdf.cell(0, 7, text, ln=True)

    def write_table(headers, rows, col_widths=None):
        if not col_widths:
            col_widths = [pdf.w / len(headers)] * len(headers)
        pdf.set_font("zh", "B", 9)
        for h, w in zip(headers, col_widths):
            pdf.cell(w, 8, h, border=1)
        pdf.ln()
        pdf.set_font("zh", "", 8)
        for row in rows:
            for cell, w in zip(row, col_widths):
                pdf.cell(w, 7, str(cell)[:30], border=1)
            pdf.ln()
        pdf.ln(4)

    # 封面
    write_title("AI Hedge Fund 分析报告", 20)
    write_normal(f"生成时间: {run_time}")
    write_normal(f"分析标的: {', '.join(tickers)}")
    write_normal(f"分析师: {len([k for k in signals if k != 'risk_management_agent'])} 位")
    pdf.ln(6)

    # 摘要
    write_title("一、最终决策摘要", 14)
    summary_rows = []
    for t in tickers:
        d = decisions.get(t, {})
        summary_rows.append([
            t, d.get("action", "-").upper(), str(d.get("quantity", 0)),
            f"{d.get('confidence', 0)}%", d.get("reasoning", "-")[:40]
        ])
    write_table(["股票", "操作", "数量", "置信度", "理由"], summary_rows,
                [30, 20, 20, 20, pdf.w - 90])

    # 信号矩阵
    write_title("二、分析师信号矩阵", 14)
    agent_keys = [k for k in signals.keys() if k != "risk_management_agent"]
    matrix_rows = []
    for t in tickers:
        for ak in agent_keys:
            s = signals.get(ak, {}).get(t, {})
            matrix_rows.append([
                t, ak, s.get("signal", "-").upper(),
                str(s.get("confidence", 0)), s.get("reasoning", "-")[:40]
            ])
    write_table(["股票", "分析师", "信号", "置信度", "推理"], matrix_rows,
                [25, 40, 20, 20, pdf.w - 105])

    # 风险
    write_title("三、风险与仓位数据", 14)
    risk_rows = []
    for t in tickers:
        r = risk.get(t, {})
        vol = r.get("volatility_metrics", {})
        risk_rows.append([
            t, str(r.get("current_price", "-")),
            f"{r.get('remaining_position_limit', 0):,.0f}",
            f"{vol.get('annualized_volatility', 0):.1%}",
            str(vol.get("data_points", 0))
        ])
    write_table(["股票", "价格", "仓位上限", "年化波动", "数据天数"], risk_rows,
                [30, 30, 40, 30, pdf.w - 130])

    # 免责
    pdf.ln(6)
    pdf.set_font("zh", "", 8)
    pdf.multi_cell(0, 5,
        "免责声明: 本报告由 AI Hedge Fund Skill 自动生成，所有交易建议仅用于研究和教育目的，"
        "不构成投资建议。过去表现不代表未来结果。真实交易前请咨询持牌投资顾问。使用者自负盈亏。")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    pdf.output(output_path)
    return output_path


def main():
    p = argparse.ArgumentParser(description="从 run_fund.json 生成 PDF 报告")
    p.add_argument("--input", required=True, help="run_fund.py 输出的 JSON 文件")
    p.add_argument("--output", help="输出 PDF 路径（默认 report_<timestamp>.pdf）")
    p.add_argument("--html", action="store_true", help="强制生成 HTML 而不是 PDF")
    args = p.parse_args()

    data = json.loads(Path(args.input).read_text(encoding="utf-8"))
    output = args.output or f"results/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    if args.html or not HAS_FPDF:
        out_path = generate_html_report(data, output.replace(".pdf", ".html"))
    else:
        out_path = generate_pdf_report(data, output)

    print(f"[report] 报告已生成: {out_path}")


if __name__ == "__main__":
    main()
